apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15.4
          args: ["agent", "-dev", "-client=0.0.0.0"]
          ports:
            - containerPort: 8500
            - containerPort: 8600
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  ports:
    - port: 8500
      targetPort: 8500
      name: http
    - port: 8600
      targetPort: 8600
      protocol: UDP
      name: dns
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-gateway
  template:
    metadata:
      labels:
        app: notes-gateway
    spec:
      containers:
        - name: notes-gateway
          image: dovakin0007/notes-gateway:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: notes-gateway
spec:
  selector:
    app: notes-gateway
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  type: NodePort
